// Shared HTML helpers for report generators.

const BASE_CSS = `
  @font-face {
    font-family: 'Pretendard';
    src: local('Pretendard'), local('Pretendard-Regular');
    font-weight: 400;
  }
  body { font-family: 'Pretendard', -apple-system, BlinkMacSystemFont, 'Noto Sans KR', sans-serif; color: #0f172a; }
  h1 { font-size: 24pt; margin-bottom: 4pt; }
  h2 { font-size: 16pt; margin-top: 24pt; margin-bottom: 8pt; border-bottom: 2px solid #1d4ed8; padding-bottom: 4pt; }
  table { width: 100%; border-collapse: collapse; margin-top: 8pt; font-size: 10pt; }
  th, td { border: 1px solid #cbd5e1; padding: 6pt 8pt; text-align: left; }
  th { background: #f1f5f9; font-weight: 600; }
  .meta { color: #64748b; font-size: 10pt; }
  .summary-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 8pt; margin-top: 12pt; }
  .summary-card { border: 1px solid #cbd5e1; padding: 10pt; border-radius: 4pt; }
  .summary-card .label { font-size: 9pt; color: #64748b; text-transform: uppercase; }
  .summary-card .value { font-size: 20pt; font-weight: 700; }
  .badge { display: inline-block; padding: 2pt 6pt; border-radius: 999px; font-size: 9pt; font-weight: 600; }
  .badge-overdue { background: #fee2e2; color: #b91c1c; }
  .badge-imminent { background: #fef3c7; color: #b45309; }
  .badge-normal { background: #d1fae5; color: #065f46; }
  footer { margin-top: 24pt; font-size: 9pt; color: #94a3b8; text-align: center; }
`;

export function wrapHtml(title: string, body: string): string {
  return `<!doctype html>
<html lang="ko">
<head>
  <meta charset="utf-8">
  <title>${escapeHtml(title)}</title>
  <style>${BASE_CSS}</style>
</head>
<body>${body}
<footer>Generated by MetroAI · ${new Date().toLocaleString('ko-KR')}</footer>
</body></html>`;
}

export function escapeHtml(text: string | null | undefined): string {
  if (text == null) return '-';
  return String(text)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

export function formatDate(value: Date | string | null): string {
  if (!value) return '-';
  const d = typeof value === 'string' ? new Date(value) : value;
  return new Intl.DateTimeFormat('ko-KR', { year: 'numeric', month: '2-digit', day: '2-digit' }).format(d);
}
